tensorflow/recommenders-addons

.github/workflows/notify_codeowners.py

[fix] notify owner fail

---

.github/workflows/release.yml
README.md
tensorflow_recommenders_addons/dynamic_embedding/core/ops/cuckoo_hashtable_ops.cc

[refactor] remove allowlist for better compatibility

[refactor] remove allowlist for better compatibility

---

tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py

[Feat] ModelMode setting APIs for thread-safety on inference

[Feat] ModelMode setting APIs for thread-safety on inference

---

tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py

Change self.init_size to self._init_size in cuckoo_hashtable_ops.py

Change self.init_size to self._init_size in cuckoo_hashtable_ops.py

---

.github/workflows/ci_test.yml
docs/tutorials/_toc.yaml
docs/tutorials/basic_ranking_with_dynamic_embedding.ipynb

add embedding_lookup doc

---

WORKSPACE
build_deps/build_pip_pkg.sh

Add workspace(name = tf_recommenders_addons) to the WORKSPACE file.

Add workspace(name = tf_recommenders_addons) to the WORKSPACE file.

---

tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py

add GraphKeys for dynamic_embedding_variable

---

tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py

- [ x] Bug fix
- [ x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/recommenders-addons/blob/master/CONTRIBUTING.md#coding-style)
- [ x] I have added tests that prove my fix is effective or that my feature works
*

[fix] embeddings shape for embedding_lookup

---

docs/tutorials/embedding_variable_tutorial.ipynb
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
tensorflow_recommenders_addons/embedding_variable/__init__.py
tensorflow_recommenders_addons/embedding_variable/core/kernels/embedding_var.h
tensorflow_recommenders_addons/embedding_variable/core/kernels/ev_ops.cc
tensorflow_recommenders_addons/embedding_variable/core/ops/ev_ops.cc
tensorflow_recommenders_addons/embedding_variable/python/ops/BUILD
tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable_ops.py
tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable_ops_test.py
tensorflow_recommenders_addons/embedding_variable/python/optimizers/adagrad.py
tensorflow_recommenders_addons/embedding_variable/python/optimizers/adam.py

- Embedding support adam/adagrad optimizer
- add EmbeddingVariable Unittest
- refine EmbeddingVariable code

EmbeddingVariable support adagrad/adam optimizer

---

.github/workflows/release.yml
CONTRIBUTING.md
README.md
docs/README.md
docs/api_docs/README.md
docs/api_docs/dynamic_embedding.md
docs/api_docs/dynamic_embedding/ModelMode.md
docs/api_docs/dynamic_embedding/TrainableWrapper.md
docs/api_docs/dynamic_embedding/Variable.md
docs/api_docs/dynamic_embedding/embedding_lookup.md
docs/api_docs/dynamic_embedding/embedding_lookup_sparse.md
docs/api_docs/dynamic_embedding/enable_inference_mode.md
docs/api_docs/dynamic_embedding/enable_train_mode.md
docs/api_docs/dynamic_embedding/get_model_mode.md
docs/api_docs/dynamic_embedding/get_variable.md
docs/api_docs/dynamic_embedding/safe_embedding_lookup_sparse.md
docs/tutorials/dynamic_embedding_tutorial.ipynb
setup.py
tensorflow_recommenders_addons/version.py

- update docs for release0
- add Acknowledgment & notice

[refactor] prepare for release version

---

README.md

[README.md]Compatility with Tensorflow Serving

[README.md]Compatility with Tensorflow Serving

---

README.md
docs/README.md
docs/tutorials/_toc.yaml

[doc] update readme & tutorial link

---

tensorflow_recommenders_addons/version.py

modify version to v0.1.0 for release

[test]modify version to v0.1.0 for release

---

.github/workflows/backport.yml

[fix]batch port bot error

---

docs/api_docs/dynamic_embedding.md
docs/api_docs/dynamic_embedding/DynamicEmbeddingOptimizer.md
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py

[doc]add API doc for dynamic_embedding.DynamicEmbeddingOptimizer

[doc]add API doc for dynamic_embedding.DynamicEmbeddingOptimizer

---

tensorflow_recommenders_addons/utils/ensure_tf_install.py

[fix] wrong TF version warning

[fix] wrong TF version warning

---

STYLE_GUIDE.md

Add code formating method for bazel BUILD files.

Add style guide for bazel BUILD files.

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/cuckoo_hashtable_ops_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/restrict_policies_test.py

missing commit for the PR:
https://github.com/tensorflow/recommenders-addons/pull/57

[fix] optimized hashtable not work

---

demo/movielens-1m-ps/README.md
demo/movielens-1m-ps/movielens-1m-ps.py
demo/movielens-1m-ps/start.sh
demo/movielens-1m-ps/stop.sh

[demo] add a distributed training demo on movielens for dynamic_embedding

[demo] add a distributed training demo on movielens for dynamic_embedding

---

.gitignore
docs/api_docs/dynamic_embedding.md
docs/api_docs/dynamic_embedding/embedding_lookup_unique.md
tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py

[feat] add dynamic_embedding.embedding_lookup_unique API.

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cub/cub/grid/grid_barrier.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cub/cub/util_allocator.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cudf/concurrent_unordered_map.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/nv_hashtable.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/nv_multigpu.cuh

GPU supoorts Unified Memory.
cudaMalloc -> cudaMallocManaged

GPU supports Unified Memory

---

README.md
build_deps/tf_dependency/build_defs.bzl.tpl
build_deps/tf_dependency/tf_configure.bzl
configure.py
tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
tensorflow_recommenders_addons/tensorflow_recommenders_addons.bzl

Support TF Serving compilation.

Support TF Serving compilation

---

.github/workflows/release-drafter.yml

[CI]release-drafter fail for shortened SHA

[CI]release-drafter fail for shortened SHA

---

tensorflow_recommenders_addons/version.py

[CI]change version to 0.2.0

---

.github/workflows/release.yml

[CI-fix]no need macOS GPU version

[CI-fix]no need macOS GPU version

---

tensorflow_recommenders_addons/dynamic_embedding/python/ops/math_ops.py

[OPT] math ops use GPU op when GPU avaliable

[OPT] math ops use GPU op when GPU avaliable

---

tensorflow_recommenders_addons/version.py

[CI] change version to 0.2.0 without dev

[CI] change version to 0.2.0 without dev

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu.h
tensorflow_recommenders_addons/dynamic_embedding/core/ops/cuckoo_hashtable_ops.cc
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py

New Feature: add dynamic_embedding.Variable clear op

add dynamic_embedding.Variable clear

---

rfcs/20200424-sparse-domain-isolation.md

- Add DynamicEmbeddingOptimizer to RFC to avoid misunderstanding.

[doc] add DynamicEmbeddingOptimizer to rfc

---

README.md

from issue : https://github.com/tensorflow/recommenders-addons/issues/97

[doc-fix]add TF_VERSION to env.

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc

[fix] Import of GPUHashTable should clear first.

[fix] Import of GPUHashTable should clear first.

---

STYLE_GUIDE.md

[fix] style guide spell error

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu.h
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu.h
tensorflow_recommenders_addons/dynamic_embedding/core/lib/cuckoo/cuckoohash_map.hh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cudf/concurrent_unordered_map.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/nv_hashtable.cuh
tensorflow_recommenders_addons/dynamic_embedding/core/ops/cuckoo_hashtable_ops.cc
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py

[feat] add Accum and FindWithExists APIs for CPU&GPU hashtable
- These API will help relieve stale gradient problem in large-scale asynchronous training.

[feat] add Accum and FindWithExists APIs for hashtable

---

demo/embedding_variable/ev-norm-local.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
tensorflow_recommenders_addons/embedding_variable/__init__.py
tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable.py
tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable_ops.py

EmbeddingVarialbe support partitioner

---

README.md
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu_impl_int32_float_0.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu_impl_int32_float_1.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu_impl_int32_float_2.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu_impl_int32_float_3.cu.cc
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py

[feat] add supported key-value type(int32, float32) for GPU

[feat] add supported key-value type(int32, float32) for GPU

---

tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.h
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.h
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.h

In some system environments you must add linking options to use POSIX libraries. Fixes #187 
Also fix FindWithExist function in Redis backend. 
And fix TFRA being not able to be compiled under TF 2.6 via changing declaration "PersistentTensor" to "Tensor".
Build it again.

[fix]Compile compatibility to TF2.6. Add '-lrt' for Redis backend. Fix FindWithExist function in Redis backend.

---

demo/dynamic_embedding/movielens-100k-estimator-with-warmup/README.md
demo/dynamic_embedding/movielens-100k-estimator-with-warmup/export.sh
demo/dynamic_embedding/movielens-100k-estimator-with-warmup/movielens-100k-estimator.py
demo/dynamic_embedding/movielens-100k-estimator-with-warmup/stop.sh
demo/dynamic_embedding/movielens-100k-estimator-with-warmup/train.sh
demo/dynamic_embedding/movielens-100k-estimator-with-warmup/warmup_train.sh

add movielens-100k-estimator-with-warmup

[demo] add movielens-100k-estimator-with-warmup

---

tensorflow_recommenders_addons/__init__.py

- tfra.__version__ is always "v0.1.0"

[fix]__version__ is always "v0.1.0"

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py

[fix]Make up a exception handling.
[fix]Fix redis test unable to run.
Remove the lock when choosing the thread context, and then improve performance.
Also fix some little bug.
Most performance improving in pulling data.

[Feat]Remove the lock when choosing the thread context.

---

docs/api_docs/tfra/dynamic_embedding.md
docs/api_docs/tfra/dynamic_embedding/CuckooHashTableConfig.md
docs/api_docs/tfra/dynamic_embedding/CuckooHashTableCreator.md
docs/api_docs/tfra/dynamic_embedding/DynamicEmbeddingOptimizer.md
docs/api_docs/tfra/dynamic_embedding/GraphKeys.md
docs/api_docs/tfra/dynamic_embedding/RedisTable.md
docs/api_docs/tfra/dynamic_embedding/RedisTableConfig.md
docs/api_docs/tfra/dynamic_embedding/RedisTableCreator.md
docs/api_docs/tfra/dynamic_embedding/TrainableWrapper/SaveSliceInfo.md
docs/api_docs/tfra/dynamic_embedding/Variable.md
docs/api_docs/tfra/dynamic_embedding/embedding_lookup.md
docs/api_docs/tfra/dynamic_embedding/embedding_lookup_sparse.md
docs/api_docs/tfra/dynamic_embedding/embedding_lookup_unique.md
docs/api_docs/tfra/dynamic_embedding/get_variable.md
docs/api_docs/tfra/dynamic_embedding/keras.md
docs/api_docs/tfra/dynamic_embedding/keras/layers.md
docs/api_docs/tfra/dynamic_embedding/keras/layers/BasicEmbedding.md
docs/api_docs/tfra/dynamic_embedding/keras/layers/FieldWiseEmbedding.md
docs/api_docs/tfra/dynamic_embedding/keras/layers/SquashedEmbedding.md
docs/api_docs/tfra/dynamic_embedding/keras/layers/embedding.md
docs/api_docs/tfra/dynamic_embedding/keras/layers/embedding/reduce_pooling.md
docs/api_docs/tfra/dynamic_embedding/math.md
docs/api_docs/tfra/dynamic_embedding/math/sparse_fill_empty_rows.md
docs/api_docs/tfra/dynamic_embedding/math/sparse_reshape.md
docs/api_docs/tfra/dynamic_embedding/safe_embedding_lookup_sparse.md
docs/api_docs/tfra/dynamic_embedding/shadow_ops.md
docs/api_docs/tfra/dynamic_embedding/shadow_ops/ShadowVariable.md
docs/api_docs/tfra/dynamic_embedding/shadow_ops/embedding_lookup.md
tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py

1. Add keras module into dynamic_embedding for auto-generating docs.
2. Update API docs

[Doc] Update api docs

---

tensorflow_recommenders_addons/version.py

[CI] change dev version to 0.4.0

[CI] change dev version to 0.4.0

---

tensorflow_recommenders_addons/version.py

- [release] change version to 0.4.0 without dev

[release] change version to 0.4.0 without dev

---

demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/movielens-100k-estimator.py

[fix]  demo issue for 'horovod_synchronous' -> 'synchronous'

[fix]  demo issue for 'horovod_synchronous' -> 'synchronous'

---

tools/docker/dev_container.Dockerfile

[fix] stopping the Bazel in dev docker to update automatically .

[fix] stopping the Bazel in dev docker to update automatically .

---

tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py

fix(comment): Fix error in comment

---

.github/workflows/github_build_dev_container.sh
tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
tools/build_dev_container.sh
tools/docker/dev_container.Dockerfile
tools/docker/install/install_nccl.sh
tools/testing/build_and_run_tests.sh

- Make dev container can run GPU tests.
- Fix some issue of UTs for GPU env

[CI] enable unit test on GPU in dev container.

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc

[feat] Avoid reallocating and copying device memory when the inputs of the Remove and ImportValues functions are already device variables.
Sometimes the input keys and values from TensorFlow Eigen tensor are already device variable with device pointer. There is no need to copy them inside the device memory.
Just load model and print pointer type in C++ code.

[feat] Avoid reallocating and copying device memory when the inputs of the Remove and ImportValues functions are already device variables.

---

.github/workflows/make_wheel_Linux_x86.sh
.github/workflows/release.yml
CONTRIBUTING.md
README.md
configure.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
tensorflow_recommenders_addons/version.py
tools/build_dev_container.sh
tools/docker/cpu_tests.Dockerfile
tools/docker/cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython.Dockerfile
tools/install_deps/tensorflow-cpu.txt
tools/install_deps/tensorflow.txt
tools/run_gpu_tests.sh

- [CI] switch TF version to 2.8.3 and 2.6.3

[release] change version to 0.5.0 without dev

---

.github/workflows/make_wheel_macOS_arm64.sh
README.md
build_deps/build_pip_pkg.sh
configure.py
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/warm_start_util_test.py
tensorflow_recommenders_addons/version.py

Fixed building errors for apple silicon devices
- Fixed broken code found during the apple silicon build test
- Updated the apple silicon build script
- Updated apple silicon's build instruction, unsupported APIs and frameworks on the README file
Manually tested by calling test scripts on `dynamic_embedding/python/kernel_tests/`

[fix] Fixed apple silicon compile errors

---

.github/workflows/make_wheel_macOS_arm64.sh
.github/workflows/make_wheel_macOS_x86.sh
README.md
build_deps/build_pip_pkg.sh
configure.py
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/warm_start_util_test.py
tensorflow_recommenders_addons/version.py

The 2 fixes on release:
- [fix] Apple silicon compile errors
- [Fix] CI error for wheel update.

[fix] Apple silicon compile errors

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu.h

Fix bug that rehash might not be triggered

---

.github/workflows/backport.yml
.github/workflows/make_wheel_Linux_x86.sh
.github/workflows/release.yml
WORKSPACE
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
tools/check_python_format.py
tools/docker/cuda11.2.1-cudnn8-ubuntu20.04-manylinux2014-multipython.Dockerfile
tools/docker/install/install_deb_packages.sh
tools/docker/install/install_latest_clang.sh
tools/docker/install/install_nccl.sh
tools/docker/install/install_pip_packages_by_version.sh
tools/docker/sanity_check.Dockerfile

- Simplify the CI pipeline by removing some unnecessary testing items.
- Fix the hiredis dependency to tag v1.1.0

[CI] update CI docker to ubuntu20.04

---

tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py

Fix logic of updating TrainableWrapper with `bp_v2` option
- [ x ] Bug fix
- [ x ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/recommenders-addons/blob/master/CONTRIBUTING.md#coding-style)
- [ x ] By running yapf
*

fix: Reverse update logic within bp_v2

---

tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py

Clear the table, or the following test assertions will be affected

Fixed redis table unit test

---

tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py

- Add `unique` operation to `keras.layers.BasicEmbedding`
- Add  `keras.layers.Embedding` as the alias of `keras.layers.BasicEmbedding`

[Feat] Add `unique` to `keras.layers.BasicEmbedding`

---

README.md
tensorflow_recommenders_addons/dynamic_embedding/core/ops/redis_table_ops.cc
tools/config_tfserving.sh
tools/docker/serving-devel-gpu.Dockerfile
tools/docker/serving-devel.Dockerfile
tools/serving_padding/.bazelrc_gpu_padding
tools/serving_padding/.bazelrc_padding

- Fix a multi-define issue caused by `ValidateTableResourceHandle` on serving context.

[Feat] Add tf-serving config shell script

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h

[opt] Optimize memory usage when saving and loading hkv

---

tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py

[fix] Fixed setting FileSystemSaver buffer_size does not take effect

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h

[fix] fixed hkv cuda misalign in tf2.15

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h

[fix] Fixed buffer_size setting when hkv loads and saves files

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h

set retry_on_failure to false for tf allocator
*

[opt] set retry_on_failure to false for tf allocator

---

demo/dynamic_embedding/movielens-1m-keras-with-horovod/README.md
demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/tf_patch_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py

add tf patch for TensorShape.as_list to allow dynamic shape
fix horovod example
add DEResourceVariable to __init__.py  to allow use it by de.DEResourceVariable
*

[Bug Fix] add tf patch for TensorShape.as_list to allow dynamic shape

---

demo/dynamic_embedding/movielens-1m-keras-with-horovod/README.md
demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
tensorflow_recommenders_addons/dynamic_embedding/__init__.py
tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/tf_patch_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py

cherry pick two commits for r0.7 branch
*

[Bug Fix] add tf patch for TensorShape.as_list to allow dynamic shape 

---

tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops.h
tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops_impl.h
tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/warm_start_util_test.py
tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
tools/docker/cpu_tests.Dockerfile
tools/testing/build_and_run_tests.sh

Fix build errors under tf 2.16.2
*

[FIX] upgrade to tf 2.16.2

---

tensorflow_recommenders_addons/version.py

[CI] switch the version to regular 0.8.0

---

.github/workflows/release.yml
tensorflow_recommenders_addons/version.py

[fix] only upload wheel with tf 2.16.2 due to pip limitation
