- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/cuckoo_hashtable_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/cuckoo_hashtable_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tools/docker/cpu_tests.Dockerfile
- tools/docker/sanity_check.Dockerfile
- tools/testing/build_and_run_tests.sh
**Set the init_size_ parameter mode**
1. Set environment variable
```
export TF_HASHTABLE_INIT_SIZE=100000000
```
2. Set get_variable parameter
```
import tensorflow as tf
import tensorflow_recommenders_addons.dynamic_embedding as de
w = de.get_variable(name="dynamic_embeddings",
devices=["/job:ps/replica:0/task:0/CPU:0",],
initializer=tf.random_normal_initializer(0, 0.005),
dim=8,
init_size=100000000)
```
3. Default
```
1024 * 8,  // 8192 KV pairs by default
```
> Support custom init_size_ parameter for cuckoohash_map.

- tensorflow_recommenders_addons/dynamic_embedding/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/restrict_policies_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/restrict_policies.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
This PR provides the capability of tracking and restricting the sparse variables and optimizer slots in training.
* [RestrictPolicy](): Abstract class which defines rules for tracking and updating the variables and optimizer slots.
* [TimestampRestrictPolicy](): Derived class from `RestrictPolicy` follow the "oldest-out-first" rule.
* [FrequencyRestrictPolicy](): Derived class from `RestrictPolicy` follow the "lowest-occurrence-out-first" rule.
```python
var = dynamic_embedding.get_variable(
'my_var',
initializer=0.1,
dim=8,
restrict_policy=de.FrequencyRestrictPolicy)
...
optimizer.minimize(loss_fn, var_fn)
if step % 20 == 0:
var.restrict(100, trigger=120)
```
```python
var = dynamic_embedding.get_variable(
'my_var',
initializer=0.1,
dim=8,
restrict_policy=de.TimestampRestrictPolicy)
... …
```
> Support restricted variable

- docs/tutorials/dynamic_embedding_tutorial.ipynb
wrap the optimizer in tfra.dynamic_embedding.DynamicEmbeddingOptimizer
Fixes # 41 Bug: Dynamic embedding is not included in model.trainable_variables.
*
> [doc-fix] wrap the optimizer in tfra.dynamic_embedding.DynamicEmbeddingOptimizer

- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int32_double.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int32_float.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int32_int32.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_double.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_float.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_half.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_int32.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_int64.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_int8.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_int64_tstring.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_bool.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_double.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_float.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_half.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_int32.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_int64.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu_impl_tstring_int8.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/cuckoo/cuckoohash_config.hh
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
1. reduce memory consuming of de.Variable 
2. support string type Keys and Values.
3. switch the hash function to murmur hash when Key type is int64.
> [opt] reduce memory consuming of de.Variable and support string type Keys and Values.

- build_deps/toolchains/gpu/cuda_configure.bzl
I tried to build a TF-GPU op under tfra/dynamic_embedding framework, but get error in [issue](https://github.com/tensorflow/recommenders-addons/issues/52).
There is a running error in building script, which ignore invalid environment string.
The problem is solved by this PR.
> Fix bazel build error with cuda

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
Remove ‘LaunchTensorsInsert num_worker_threads’ log printing.
During training, the log prints too much.
> Remove ‘LaunchTensorsInsert num_worker_threads’ log printing.

- demo/movielens-100k-estimator/README.md
- demo/movielens-100k-estimator/export.sh
- demo/movielens-100k-estimator/movielens-100k-estimator.py
- demo/movielens-100k-estimator/stop.sh
- demo/movielens-100k-estimator/train.sh
> add estimator demo

- README.md
- build_deps/tf_dependency/build_defs.bzl.tpl
- build_deps/tf_dependency/tf_configure.bzl
- build_deps/toolchains/gpu/cuda_configure.bzl
- configure.py
- tensorflow_recommenders_addons/dynamic_embedding/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops_impl.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops_impl.h
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/math_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/math_grad_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/math_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/restrict_policies_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/math_grad.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/math_ops.py
- tensorflow_recommenders_addons/tensorflow_recommenders_addons.bzl
- tools/docker/sanity_check.Dockerfile
- tools/pre_commit_format.py
`SparseSegmentSum` and `SparseSegmentSumWithNumSegments` are two important opeartions in sparse training and inference. Currently, there are no GPU impl in Tensorflow for them.
This PR provide GPU version of `SparseSegmentSum` and `SparseSegmentSumWithNumSegments`
> Support sparse_segment_sum ops on GPU.

- README.md
added the way to compile GPU Serving.
> [doc]update readme, added the way to compile GPU Serving.

- README.md
- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_fill_empty_rows_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_fill_empty_rows_op.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_fill_empty_rows_op.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_reshape_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_reshape_op.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/sparse_reshape_op.h
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/math_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/math_grad_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/math_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/math_grad.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/math_ops.py
Add GPU operator: sparse_fill_empty_rows and sparse_reshape
*
> [feat] Add GPU operator: sparse_fill_empty_rows and sparse_reshape

- tensorflow_recommenders_addons/embedding_variable/python/ops/embedding_variable_ops.py
In graph mode, report_uninitialized_variables use state_ops.is_variable_initialized to compose is_initialized_op, for ResourceVariable, this method will call BsaeResourceVariable.is_initialized method to insert this op into graph.
EmbeddingVariable should override this method so that ev_is_initailed_op can be composed into report_uninitialized_variables.
> [fix] embedding variable is_initialized not executed  in graph mode

- demo/bpv2/README.md
- demo/bpv2/bpv2.py
- demo/bpv2/stop.sh
- demo/bpv2/train.sh
- docs/api_docs/tfra/dynamic_embedding/Variable.md
- docs/api_docs/tfra/dynamic_embedding/get_variable.md
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
DE of tfra used to update embeddings / slots of embeddings by *setting* values, which introduces race condition problem among workers.
This PR solves this problem by updating MHTs of DE using the `CuckooHashTable.Accum`.
*  see `./demo/bpv2/*`
*  see `./tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py`
> [feat] bpv2 (update de by adding delta instead of setting)

- demo/amazon-us-reviews-digital-video-games/README.md
- demo/amazon-us-reviews-digital-video-games/feature.py
- demo/amazon-us-reviews-digital-video-games/main.py
- demo/amazon-us-reviews-digital-video-games/video_game_model.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_optimizer_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/restrict_policies_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/restrict_policies.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
This PR makes Keras APIs become compatible to TFRA, and also fixes the save/restore issue in TensorFlow 2.x version.
Thanks to @ccsquare 's suggestions on save/restore.
* #44 
* #47  
* #115
> Support Keras APIs and fix save-restore issue in TF2

- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
Brief Description of the PR: In graph mode, when the device context is explicitly specified by `device` or `replica_device_setter`, the session may raise incompatible error if the devices cannot be merged. This PR fixed the case.
*  [demo](https://github.com/tensorflow/recommenders-addons/tree/master/demo/movielens-1m-ps)
> Fix bug: incompatible jobs with explicit placement.

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
Command "KEYS" was used in the GetKeyBucketsAndOptimizerParamsWithName function by DE redis backend. But Command "KEYS" may cause lots of trouble, such as a serious service delay. Command "SCAN" should be a better choice. In fact, "KEYS" are banned in many companies' Redis services.
Fixes #179 
What's more, add the ability to set hashtags via Redis cluster servers slots.
run it again.
> [Fix]change 'KEYS' command in GetKeyBucketsAndOptimizerParamsWithName function to 'SCAN' command

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
Fixed a serious bug where the "myself,master" field in the node information returned by the "CLUSTER NODES" command was not being processed correctly.
> [fix]Fix misprocessing of "CLUSTER NODES" return

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
This pr is to remove `batch_reduce_to` call on the gradients for optimizer v2. In the [optimzer v2 base class](https://github.com/tensorflow/tensorflow/blob/919a858f97dfdb219ea3d1a084b594bfa520ef59/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L668), the gradients are aggregated already. 
*
> Do not batch reduce as keras optimzer already does.

- .github/workflows/release.yml
[CI]after github action updated, we cancel python3.6 for MacOS
- How to update Python to 3.7 [Guide](https://stackoverflow.com/questions/51279791/how-to-upgrade-python-version-to-3-7)
> [CI]after github action updated, we cancel python3.6 for MacOS

- docs/api_docs/tfra/dynamic_embedding/RedisBackend.md
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/README.md
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
Add storage_slice_import parameter for easy rehashing table.
Also sorting cluster_slots after get it.
Also allow not to set expire to buckets
Fix many bug when rehash(rebuckets), but there are still lots of bugs.
set storage_slice_import in redis backend config file.
> [feat] Add storage_slice_import parameter for easy rehashing table.

- .github/workflows/release.yml
- After this we'll resolve the CI fail issue that's caused by https://github.com/bazelbuild/rules_foreign_cc/archive/refs/tags/0.0.9.zip
> [CI] remove CI on TF1.15.2

- WORKSPACE
- build_deps/toolchains/redis/hiredis.BUILD
- build_deps/toolchains/redis/redis-plus-plus.BUILD
- configure.py
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
Updated rules_foreign_cc from 0.0.9 to 0.6.0, modified API names according to its document.
Picked Heka's commit which modified Redis backend for supporting Arm64.
Tested building hiredis and redis++ on macOS Arm64 m1 machine.
> [fix] Updated rules_foreign_cc from 0.0.9 to 0.6.0

- tools/docker/build_wheel.Dockerfile
- tools/docker/cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython.Dockerfile
- tools/docker/install/install_rocksdb.sh
- Install RocksDB and its deps to CI docker image by following [RocksDB install guide](https://github.com/facebook/rocksdb/blob/main/INSTALL.md).
> [CI] Install RocksDb and its dependency to CI docker image.

- .github/workflows/make_wheel_Linux.sh
- .github/workflows/release.yml
- build_deps/toolchains/gcc7_manylinux2010-nvcc-cuda11/cc_toolchain_config.bzl
- build_deps/toolchains/gpu/crosstool/CROSSTOOL.tpl
- build_deps/toolchains/gpu/crosstool/cc_toolchain_config.bzl.tpl
- build_deps/toolchains/gpu/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc.tpl
- build_deps/toolchains/gpu/cuda_configure.bzl
- configure.py
- setup.py
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/segment_reduction_ops_impl.h
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/version.py
Avoid Floating point exception (core dumped) when using RedisTable by empty ids inputs. I'm ignoring that and that's what's going to happen dividing by zero.
Also make compatible with the optimizers inited from tf.keras.optimizers. Optimizers call from tf.keras.optimizers are not belong to the class optimizer_v2.OptimizerV2 when using tf2.6.
Add TF2.7.0 CI. 
Add CUDA_COMPUTE_CAPABILITIES.
Delete Python 3.6 in CI.
Make compatible with TF2.7 in reduction_ops_impl.h
Tensorflow2.7 requires C++14 or above, changing the standard for CUDA compilation from C++11 to C++14.
**About RedisTable**
```
import numpy as np
import tensorflow as tf
import tensorflow_recommenders_addons as tfra
redis_config = tfra.dynamic_embedding.RedisTableConfig(
redis_config_abs_dir="test/config1.json")
redis_creator = …
```
> [fix]Avoid Floating point exception (core dumped) when using RedisTable by empty ids inputs.

- .github/workflows/make_wheel_Linux.sh
- .github/workflows/make_wheel_Windows.sh
- .github/workflows/make_wheel_macOS.sh
- .github/workflows/release.yml
- tools/docker/build_wheel.Dockerfile
- tools/docker/cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython.Dockerfile
- tools/docker/install/install_deb_packages.sh
- tools/docker/install/install_horovod.sh
- tools/docker/install/install_nccl.sh
- tools/docker/install/install_openmpi.sh
- tools/docker/install/install_rocksdb.sh
- tools/docker/install/install_trt.sh
- tools/docker/install/use_devtoolset_7.sh
- Add openmpi and horovod to CI docker as pre-PR for https://github.com/tensorflow/recommenders-addons/pull/205
- Refactor the CI docker file
>  [CI] add openmpi and horovod to base_install docker.

- .github/workflows/ci_test.yml
- .github/workflows/make_wheel_macOS_x86.sh
- .github/workflows/release.yml
- README.md
- build_deps/tf_header/README.md
- setup.py
- tools/docker/cpu_tests.Dockerfile
- tools/docker/pre-commit.Dockerfile
- tools/docker/sanity_check.Dockerfile
- tools/run_gpu_tests.sh
- [fix] add mpi & hvd installation to macOS CI and cpu_tests
- [CI] switch little tests to python3.7 for compatible with TF2.7
- [CI] fix release files name exist error and correct nightly whl name for GPU .
> [fix] add mpi & hvd installation to macOS CI and cpu_tests

- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/README.md
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/export.sh
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/movielens-100k-estimator.py
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/session_hook.py
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/start_worker.sh
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/stop.sh
- demo/dynamic_embedding/movielens-100k-sync-estimator-with-horovod/train.sh
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tools/testing/build_and_run_tests.sh
- Use horovod to sync dense grad of the model parameter,  for `TrainableWrapper`'s grad, keep same with before.
> [Feat]support horovod sync train

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
Fix an issue where tf_patch.py failed in TF >= 2.6.x. It cause by Keras detached from TF repo.
try keras initializer in TF >= 2.6.x. And there is no full-size init warning.
> [fix] Fix an issue where tf_patch.py failed in TF >= 2.6.x.

- tensorflow_recommenders_addons/dynamic_embedding/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/warm_start_util_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/warm_start_util.py
In tensorflow we use tf.train.Checkpoint(tf2) or tf.compat.v1.train.Saver(tf1) for saving/restoring model, but I found it a little hard when I use these APIs to restore part of the model in tfra to perform transfer learning. In recommendation system, it's a common trick to speed up model convergence using embedding warmup, and the dense part of the model is trained from scratch, hence partial restore. The demonstrate the API design for partial restore are as follows.
```python
restore_op = tfra.dynamic_embedding.warm_start(ckpt_to_initialize_from='/path/to/ckpt/', vars_to_warm_start='.*embeddings.*')
with tf.compat.v1.Session() as sess:
sess.run(restore_op)
...
```
- Add tfra.dynamic_embedding.warm_start to support warm-start in tfra model.
> Support warm-start in tfra.dynamic_embedding

- tools/docs/Readme.md
- tools/docs/build_docs.py
The tensorflow-docs pretty format is too compact to show the top link.
This PR make additional blank lines to avoid the overlapping between the text and icon.
> Add patch to tensorflow-docs for pretty on top link

- README.md
- build_deps/tf_header/README.md
Added Apple Silicon Installation instruction in README.md
Fixed a few typos
Run the commands in the terminal
> [Doc]Add Apple Silicon installation instruction & fix typo

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/redis_table_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
- third_party/redis_module/Makefile
- third_party/redis_module/README.md
- third_party/redis_module/avx.h
- third_party/redis_module/bpv2_hmaccum_cmd.c
- third_party/redis_module/bpv2_hmaccum_cmd.h
- third_party/redis_module/redismodule.h
new redis module to add `HMACCUM` comand to enable `bp_v2` in redis backend
pytest case test_variable_find_with_exists_and_accum
*  start a redis server
*  upsert cert KV pairs
*  remove/add some Keys
*  run accum and check K,V contents
> [Feat] add HMACCUM redis module and enable BPV2 in redis impl

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
Fixed segment fault due to lambda may capture the thread_context reference with error address when high concurrency and server disconnection.
When inference mode, kill Redis server process.
> [fix] Fixed segment fault due to lambda may capture the thread_context reference with error address

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
When set de.Variable to trainable, the optimizer will still update it, which is not expected.
*
> fix(optimizer): Bug: Variable set to trainable to false still updating embedding

- WORKSPACE
- build_deps/toolchains/redis/hiredis.BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu.h
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/hadoop_file_system/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/hadoop_file_system/hadoop_file_system.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/hadoop_file_system/hadoop_file_system.h
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/cuckoo_hashtable_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/cuckoo_hashtable_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- third_party/hadoop.BUILD
Because of the storage mechanism of tensorflow, when the embedding table is large, the worker will consume a lot of memory, and eventually OOM.
This PR provides some methods to save or load files from hdfs for dynamic embedding tables.
In the test file, you need to replace the `filepath` with the real hdfs path. In addition, you need to add the header file `third_party/hadoop/hdfs.h` of hadoop in tensorflow.
> [Feat] Save and load cuckoo hashtable from hdfs

- build_deps/toolchains/gpu/cuda_configure.bzl
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
Before this fix, in Keras model, ShadowVariable would read_value with do_prefetch twice when both embedding_lookup in forward calculation and apply_grad_to_update_var in backward calculation. For now, if var in apply_grad_to_update_var is ShadowVariable, read its value directly because it has been already done read_value with do_prefetch when in embedding_lookup function.
Also fix pass parameter init_size when create slot variable for de.Variable.
Also compatible with CUDA 11.6
Also modify _convert_anything_to_init function:
1.Make output shape is dim when raw_init is a TF Initializer
2.Make input dim is a constant op when using reshape op to prevent fault —— 
*** tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 1 values, but the requested …
> [Fix] Avoid double lookup of tables when using ShadowVariable when the Optimizer is updating gradients

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
Fix bug that user self-defined variable name would be  modified to "TrainableWrapperHandle" when Keras eager mode. Which code is copied from Tensorflow.
when using BasicEmbedding in TFRA
> [fix] Fix bug that user self-defined variable name would be  modified to "TrainableWrapper" when Keras eager mode.

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/hadoop_file_system/hadoop_file_system.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cudf/concurrent_unordered_map.cuh
[fix] Compatible with tensorflow::int64 is "long long" instead of "in…t64_t" when TensorFlow version is 2.4 or below.
[fix] Compatible with "tensorflow/core/platform/errors.h" but not "tensorflow/core/platform/error.h" when tensorflow version is greater than 2.8.
Compile TFRA with TensorFlow version 2.4 and 2.8.
> [fix] Compatible with compiling problem with TensorFlow version 2.4 and 2.8.

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/cuckoo_hashtable_ops_test.py
This PR is to fix gpu table import issues. It will expand the table to appropriate size before importing values. And it will try to minimize the number of calls to size kernel.
*
> [Fix]Rehash gpu table before importing values and reduce size kernel call.

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
Fixes https://github.com/tensorflow/recommenders-addons/issues/278
* model.py
```python
import tensorflow as tf
from tensorflow_recommenders_addons import dynamic_embedding as de
from absl import app, flags, logging
def build_model():
embedding_size = 2
user_id = tf.keras.Input(shape=(1,), name='user_id', dtype=tf.int64)
user_emb = de.keras.layers.SquashedEmbedding(embedding_size, name='user_de')(user_id)
user_emb = tf.keras.layers.Lambda(lambda x: x, name='user_emb')(user_emb)
model = tf.keras.Model({
'user_id': user_id
},
{
'user_id': user_id,
'user_emb': user_emb
})
return model
def main(_):
model = build_model()
save_options = tf.saved_model.SaveOptions(namespace_whitelist=['TFRA'])
savedmodel_dir = '/tmp/savedmodel/tfra/train/1'
model.save(savedmodel_dir, …
```
> [fix] fix shadow variable lookup race condition

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
Fix device of table shard was lost in savedmodel pb file when save model with keras api. When use keras model saving, there is no device property in TFRA table resource node. So that, it would cause problem in serving scenes when load model with TF C++ api. That is when user want a CPU table but it was treated to a GPU table without enough device memory.
In file 'tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py', a new test function 
'**test_keras_save_load_weights**'.
> [fix] fix device of table shard was lost in savedmodel pb file when save model with keras api.

- README.md
Update the apple silicon installing instructions after release 0.5.0 to PyPI
- Specified tensorflow-macos version to 2.6.0
- Added install from pip instruction
*
> [Doc] Update apple silicon instruction

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
> [fix] Remove redundant code

- tensorflow_recommenders_addons/dynamic_embedding/core/lib/nvhash/cudf/concurrent_unordered_map.cuh
Removed build warning: 'type qualifier is meaningless on cast type'
> Removed build warning: 'type qualifier is meaningless on cast type'

- build_deps/toolchains/gpu/cuda_configure.bzl
- docs/api_docs/tfra/dynamic_embedding/FileSystemSaver.md
- setup.py
- tensorflow_recommenders_addons/dynamic_embedding/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_cpu.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/shadow_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
Add the features for expanding and shrinking the number of tables in distributed training by independently saving files.
Also improve the performance of CPU table by using std::copy_n.
Also make genarating _DEFAULT_CUDA_COMPUTE_CAPABILITIES more compatible and concise in build_deps/toolchains/gpu/cuda_configure.bzl.
Also compatible with TF 2.9, which would pass parameter validate_shape to _init_from_args.
Also fix RedisTableOfTensors Node missing user-defined name.
Also fix problem with the parameter 'checkpoint' passing not working when using DE BasicEmbedding.
Also compatible with 'find_namespace_packages' when using setuptools, because 'find_packages' has been deprecated.
Read the doc(docs/api_docs/tfra/dynamic_embedding/FileSystemSaver.md) and run new tests.
> [Feat]Add the features for expanding and shrinking the number of tables in distributed training by independently saving files.

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
Fix error that self._saveable_fn would not exist when checkpoint param is False.
Also make BasicEmbedding call function more grace.
use get_variable calling and set checkpoint=False.
> [Fix] fix error that self._saveable_fn would not exist when checkpoint param is False.

- .github/workflows/ci_test.yml
- .github/workflows/make_wheel_Linux.sh
- .github/workflows/make_wheel_Windows.sh
- .github/workflows/make_wheel_macOS.sh
- .github/workflows/release.yml
- WORKSPACE
- build_deps/toolchains/redis/hiredis.BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
- tensorflow_recommenders_addons/version.py
- tools/docker/build_wheel.Dockerfile
- tools/docker/cpu_tests.Dockerfile
- tools/docker/cuda11.2-cudnn8.1-ubuntu18.04-manylinux2010-multipython.Dockerfile
- tools/docker/sanity_check.Dockerfile
- [fix: Reverse update logic within bp_v2](https://github.com/tensorflow/recommenders-addons/pull/317)
For a longtime, we didn't publish any release on r0.3. There's a lot of change from dependencies caused the CI fail, so we have to cherry-pick many `[CI] fix xxxx` from master branch.
> [Patch v0.3.2] fix: Reverse update logic within bp_v2

- .github/workflows/make_wheel_macOS_arm64.sh
- build_deps/build_pip_pkg.sh
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/warm_start_util_test.py
- tensorflow_recommenders_addons/version.py
This merge request addresses a building error that occurs when running the macOS arm64 make wheel script. The following changes were made to fix the issue:
- Updated the `Numpy` version to a compatible version.
- Corrected `tensorflow` to `tensorflow-macos`.
- Added the macOS arm64 check back to `check_platform.py`.
- Skipped failed tests due to Apple silicon not supporting `warm_up` and `hvd`.
*  pytest
> [fix] macOS arm64 build error

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/cuckoo_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_gpu.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_pool.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
fix some core dump cases and make usage of CUDA streams more reasonable.
Including:
(1)Raise error when embedding dim in Redis server is not equal to the runtime setting dim.
(2)Checkpoint setting is inoperative when calling _gather_saveables_for_checkpoint.
(3)Remove unnecessary get_size calling, and modify table_ to a unique_ptr. And fix rehashing mechanism to make it no more unnecessary extend hash table when input keys are duplicated.
(4)Redis reply obj may be a nullptr caused memory access segmentfault.
> [fix] fix some core dump cases and make usage of CUDA streams more reasonable. Also fix ineffective checkpoint setting.

- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
- `de.save_to_file_system` not work in static mode. so `de.save_to_file_system` and `de.load_from_file_system_with_restore_function` op should be created at graph build time.
- Fix the size check op for shard_keys and shard_values is not used
*
> Fix: de.save_to_file_system not work in estimator

- README.md
> [Doc] serving with triton

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
> Fix some typing errors

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/redis_table_ops.py
When synchronous training, multiple processes write the same file will cause the following JSON decoding error, so I think there is no need to write the params back to the file.
```
[1,1]< stderr >:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py", line 179, in __init__
[1,1]< stderr >:    self.params = de.get_variable(parameter_name,
[1,1]< stderr >:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py", line 1237, in get_variable
[1,1]< stderr >:    var_ = Variable(
[1,1]< stderr >:  File "/usr/local/lib/python3.8/dist-packages/tensorflow_recommenders_addons/dynamic_embedding/python/ …
```
> [fix]fix synchronous trainging error for redis backend

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
Make saving model more easier when using HvdAllToAllEmbedding by adding save function overwriting patch in tf_save_restore_patch.py.
Also fix some import bug in tf_save_restore_patch.py.
Also fix the example in demo where the python code for keras horovod synchronous training was wrong.
I have overwritten the keras save function and now it is not necessary to save the embedding shard explicitly, as long as model.save or Keras.model.save_model is called on each rank, but tf.saved_model.save is not supported.
tf.saved_model.save can also be supported in theory, but because the obj object of the save is not necessarily the keras object, I am lazy to write it for the moment, and there is a need to talk about it.
Adding a test with HvdAllToAllEmbedding.
Follow the demo …
> [feat] Make saving model more easier when using HvdAllToAllEmbedding by adding save function overwriting patch in tf_save_restore_patch.py.

- build_deps/tf_dependency/tf_configure.bzl
removed a build warning
`WARNING: /root/.cache/bazel/_bazel_root/24ead6407f1760803002dd5e0943eb24/external/local_config_tf/BUILD:13349:8: target 'libtensorflow_framework.so.2' is both a rule and a file; please choose another name for the rule`
> [Refactor]removed a build warning

- tensorflow_recommenders_addons/dynamic_embedding/python/train/checkpoint.py
When result of importing Horovod is None, TFRA DEHvdCheckpoint would not call DE variable saving and sweeping redundant DE files.
This problem because I forgot writing the correct code when importing horovod.tensorflow is None in _de_hvd_write_fs_func. Local variable 'de dir' referenced before assignment when self._hvd is None.
Uninstalling Horovod and using DEHvdCheckpoint.
> [fix] DEHvdCheckpoint failed when importing Horovod unsuccessfully.

- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/train/checkpoint.py
User may create Checkpoint class by passing keys "model", "optimizer" and so on. So root parameter in __init__ function may be None. We need to walk through all kwargs.
Successfully run
```python
horovodrun -np 2 python tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
```
> [Fix] Support TF CheckpointManager in 2.9. And support create Checkpoint with custom model key. 

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- demo/dynamic_embedding/movielens-1m-keras/movielens-1m-keras.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/shadow_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/train/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/python/train/checkpoint.py
- tools/testing/build_and_run_tests.sh
Fix the problems which checkpointManager couldn't work properly and KV files couldn't be restored when user using a lazy build Keras model.
Also fix some DE Keras Embedding demo which couldn't run. Fixes #370 
```bash
horovodrun -np 2 tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
```
also run the demo demo/dynamic_embedding/movielens-1m-keras and demo/dynamic_embedding/movielens-1m-keras-with-horovod
> [Fix] CheckpointManager couldn't work properly and KV files couldn't be restored when user using a lazy build Keras model.

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- docs/api_docs/tfra/dynamic_embedding/keras/layers/HvdAllToAllEmbedding.md
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/models.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/horovod_sync_train_test.py
The id key may be multiple copies in one tensor before real shadow lookup when using HvdAllToAllEmbedding.
Here is how the bug happens. 
**Before ALL2ALL:**
Rank0 IDs: [0,1,1,3,3] --unique-->  [0,1,3]
Rank1 IDs: [0,1,2,2,3] --unique-->  [0,1,2,3]
**After ALL2ALL:**
Rank0 IDs: [0,0,2]
Rank1 IDs: [1,1,3,3]
Rank0 has duplicated key 0, and Rank1 has duplicated keys 1 and 3. When updating the gradient, in Rank0, the key 0 will insert twice which means only one gradient takes effect and another one was covered. That may lead to under-training, same as Rank1 because of multiple copies of key 1 and key 3.
So we need to do secondary unique operation after ALL2ALL. The first time for reducing transmission overhead, the second time for training properly.
Fix bug that de_hvd_save_model and …
> [Fix] Several bugs when using HvdAllToAllEmbedding to train model and save/restore KV files.

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_table_op_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_table_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/restrict_policies.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
- Be compatible with TensorFlow 2.15 by calling the origin python function from new directory.
- Fix some test should not be run when eager mode. Also add more new test for Redis KV backend.
- Fix Redis backend json config file would not printed when a wrong json value type was set.
- Fix check wrong array index in kvs_reply from Redis returning. Wanted to check the length of value, but the length of key was checked.
Run all test script under TF2.15 environment.
> [Feat] Compatible with TensorFlow 2.15

- build_deps/toolchains/gpu/cuda_configure.bzl
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/dynamic_partition_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/hkv_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h
- tensorflow_recommenders_addons/dynamic_embedding/core/utils/utils.h
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
Compatibility updates and some compiling log optimizations have been made.
[feat] Competible with Keras3 optimizer style.
[fix] Suppress nodiscard warnings and unused warnings by adding a new LOG_IF_ERROR macro and using proper api function.
[feat] Update the config file for new CUDNN release. Now support CUDNN 9.0+
[fix] self.params may not with saveable attribution.
use default keras.optimizers in Keras 2.12+ instead of keras.legacy.optimizers.
> [Feat] Try to compatible with Keras 3 optimizer design and support CUDNN 9.0+.

- .github/workflows/release.yml
- Some incoming features cause the GPU compilation to consume too much disk space. So, we switch the GPU CI to the self-hosted node labeled `self-hosted-gpu`.
- Revert it when we can use the larger node in the github-hosted node.
> [CI] running GPU CI on self-hosted runnners.

- tensorflow_recommenders_addons/dynamic_embedding/core/utils/utils.h
There is no definitions macro MAYBE_ADD_SOURCE_LOCATION under TF 2.13.
compile it with TF2.13
> [Fix] Compiling error in TF2.13 

- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/hkv_hashtable_op.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/hkv_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv_impl.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/hkv_hashtable_ops_test.py
- tools/docker/cpu_tests.Dockerfile
- tools/testing/build_and_run_tests.sh
Because the underlying cuckoo gpu operator is changed to hkv operator, if a user originally uses cuckoo gpu training but does not have a gpu when serving, the inference service will fail。
*
> [fix] Supported hkv cpu operator base cuckoo cpu operator

- .gitignore
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/ragged_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/shadow_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/ragged_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
1. enable ShadowVariable look up for safe_embedding_lookup_sparse
2. support ragged tensor
*
> enable ShadowVariable look up for safe_embedding_lookup_sparse

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/models.py
Fix forgot to pass hvd_rank parameter into _check_saveable_and_redirect_new_de_dir function.
Sorry, my fault.
Use  de_save_model without filesystem_saver. This hvd_rank only used for logging a warning.
> [fix] forgot to pass hvd_rank parameter inner a check function of _de_keras_save_func. 

- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
In my previous tests, there was only one TFRA Embedding object passed into the trackables in the save loading function, even though there were multiple TFRA Embedding objects in the model. 
However, we have tested that under certain composition conditions, the trackables may contain multiple TFRA Embedding, so the group of multiple loading functions should be returned.
Run the test.
> [Fix] Compatible with TF2.15 register_checkpoint_saver when multiple TFRA Embedding in one trackables.

- README.md
- WORKSPACE
- docs/api_docs/tfra/dynamic_embedding/HkvHashTableConfig.md
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/hkv_hashtable_op_gpu.cu.cc
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h
- tensorflow_recommenders_addons/dynamic_embedding/core/ops/hkv_hashtable_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/hkv_hashtable_evict_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/hkv_hashtable_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/hkv_hashtable_ops.py
> add reserved_key_start_bit option to config hkv

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_connection_util.hpp
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/restrict_policies.py
Fix tmpDirPath with fixed size may cause stack overflow in Redis backend. The char size of the entered file path may exceed 1024. Fixes #405 
Fix restrict_policy wasn't tracked when using Embedding layer. Fixes #385 
When using redis backend, enter a non-existent file path that is longer than 1024.
> [Fix] Stack overflow in Redis Backend and RestrictPolicy couldn't be saved when using DE embedding layer.

- tensorflow_recommenders_addons/conftest.py
Silence 3 warnings triggered by pytest, Since no plan to fix it right now, let's reduce the noise 
*
> [CI] Silence the warning during pytest

- .github/workflows/make_wheel_macOS_arm64.sh
- .github/workflows/release.yml
- README.md
- setup.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
- tensorflow_recommenders_addons/version.py
Brief Description of the PR: Add macOS Apple Silicon pipeline.
- Skipped Redis unit tests with `dtypes.bfloat16` because the Apple silicon-built TFRA doesn't support float16.
- Updated the Apple Silicon building script.
- Updated CICD `release.yml` to enable building and releasing Apple silicon-build TFRA wheel.
- Updated instruction in README to reflect the latest process of building from source on macOS Apple silicon.
- Updated version requirements to restrict the TensorFlow version for the macOS Apple silicon-built TFRA.
Tested in my repository's GitHub Action.
*  None
> [feat] Add macOS Apple Silicon pipeline

- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/ragged_embedding_ops.py
> [FIX] raggedtensor should pass name in the eager mode

- docs/api_docs/tfra/dynamic_embedding/HkvEvictStrategy.md
- docs/api_docs/tfra/dynamic_embedding/HkvHashTable.md
- docs/api_docs/tfra/dynamic_embedding/HkvHashTableConfig.md
Added hkv evict strategy doc
*
> [doc] Added hkv evict strategy doc

- WORKSPACE
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h
Add new setting num_of_buckets_per_alloc from HKV bata 12. It might improve performance of memory access. And this feature also reduce unessential BFC reallocating information to user when CUDA OOM.
Try to prevent billion of HKV buckets allocating small piece memory which may make BFC allocator re-chunk frequently.
In beta 11, it might print more than 10,000 info. For now, only about 1,000.
According to https://developer.nvidia.com/blog/improving-gpu-memory-oversubscription-performance/, 
which said "_In our experiments, a memory page is set to be 2 MB, which is the largest page size at which GPU MMU can operate._" and "_128-byte aligned access ensures that the CPU-GPU link and system DRAM are used efficiently._ "
And one bucket in HKV is 2048+128 bytes. So a simple calculation, …
> [Feat] Add new setting num_of_buckets_per_alloc from HKV bata 12.

- .github/workflows/make_wheel_macOS_arm64.sh
- .github/workflows/make_wheel_macOS_x86.sh
- rfcs/20200424-sparse-domain-isolation.md
- tensorflow_recommenders_addons/dynamic_embedding/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/shadow_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/distributed_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/embedding_weights.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/ragged_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
- tensorflow_recommenders_addons/dynamic_embedding/python/train/checkpoint.py
- tools/docker/build_wheel.Dockerfile
support ragged tensor in all2all HvdAllToAllEmbedding lookup  
refactor embedding variable, introduce embedding_weights interface so that  dynamic embedding variable, shadow variable, hvd variable can be easily supported in the lookup and safe_embedding_lookup_sparse
*
> [feature]support ragged tensor in all2all

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/lookup_impl/lookup_table_op_hkv.h
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/hkv_hashtable_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/embedding_weights.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/hkv_hashtable_ops.py
[fix] self._default_scores was not tracked by tensorflow graph when it's as a class property, which caused fail saving.
Sinc _default_scores was always tf.constant([], dtypes.int64), so replace it totally instead of _track_trackable it.
[fix] Inherit abc.ABC may cause metaclass conflict with other Tensorflow class.
[fix] hkv_hashtable_ops_test has duplicate variable name when test both CPU and GPU device.
[fix] Compatible with HKV asserting when init_capacity is smaller than max_bucket_size
Run this code to simulate training
```python
import json
import os
import psutil
import gc
import time
import tensorflow as tf
from tensorflow.keras.layers import (Layer, Input, Embedding, Reshape,
Concatenate, Dense, Lambda)
import tensorflow_datasets as tfds
import tensorflow_recommenders_addons as …
```
> [Fix] Untracked constant tensor cause fail to save Embedding and other bugs

- .gitignore
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/README.md
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/start.sh
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/test.sh
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/callbacks_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/ragged_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/cuckoo_hashtable_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- fix load model bug
- remove un-used self.gpu_device self.cpu_device
- enable
sh start.sh 1
to test only 1 steps_per_epoch
- add inference
- fix GPU unit tests 
*
> [FIX] horovod example and gpu unit test

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/__init__.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/dynamic_layer_normalization.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/dynamic_layer_normalization_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/models.py
add DynamicLayerNormalization since tf LayerNormalization doesn't support dynamic shape
*
> [New Feature]add normalized_emb

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/start.sh
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
> [fix]remove tracking of shadow var id

- tensorflow_recommenders_addons/dynamic_embedding/core/ops/hkv_hashtable_ops.cc
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/models.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/hkv_hashtable_evict_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_creator.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/hkv_hashtable_ops.py
Fix missing HkvHashTableExportWithScores op 
with help/collaborate from @MoFHeka and zhiheng
Fix the incompatiblity with new tf.keras.optimizers.Adagrad, it pass 0 shape tensor during the init, and we fix it by init with 0
Reduce the default buffer_size of FileSystemSaver to 4k
*
> [Fix] add HkvHashTableExportWithScores op

- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/models.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
1. [FIX] add scope_name_prefix option to control size of file name to reduce the liklyhood of file name > 255 chars
2. FIX pass in fun obj bug for file name.
*
> [FIX]add scope_name_prefix option to control size of file name 

- .github/workflows/release.yml
- README.md
- setup.py
- tensorflow_recommenders_addons/utils/resource_loader.py
combine cpu and gpu wheel so that you only need pip install tensorflow-recommenders-addons
*
> [Feat]combine cpu and gpu wheel

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
[fix] There is no signature "strict_predicate_restore" in register_checkpoint_saver fucntion from tf saved_model registration when TF version 2.9. Make a function signature inspect to be compitible.
[fix] device_lib.list_local_devices() may run fail in some case, then use CPU as default device.
Run any FileSystem Saver in TF version 2.9.3
> [Fix] Some compatibility patches for Tensorflow versions and runtime environments

- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
[Fix] register_checkpoint_saver API was not stable under TF version 2.11. Therefore, for compatibility considerations, before version 2.14, SingleDeviceSaver was used to save.
Here is the error looks like when using TF 2.9
```bash
AssertionError: Tried to export a function which references 'untracked' resource Tensor("movie_id_DELayer-parameter/DynamicEmbedding/movie_id_DELayer-shadow/m/cond/movie_id_DELayer-parameter_DynamicEmbedding_movie_id_DELayer-shadow_m_mht_1of1:0", shape=(), dtype=resource). TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly. See the information below:
Function name = b'__inference_restore_fn_5544'
Captured Tensor = …
```
> [Fix] register_checkpoint_saver API was not stable under TF version 2.11.

- .github/workflows/make_wheel_Linux_x86.sh
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_ops_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/redis_table_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/distributed_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/embedding_weights.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/ragged_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
- tools/testing/build_and_run_tests.sh
> [fix] ensure shape in the safe_embedding_lookup

- tensorflow_recommenders_addons/dynamic_embedding/core/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/keras/layers/embedding.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/dynamic_embedding_variable_test.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_optimizer.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/dynamic_embedding_variable.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/shadow_embedding_ops.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_patch.py
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/tf_save_restore_patch.py
- tensorflow_recommenders_addons/dynamic_embedding/python/train/checkpoint.py
Sometimes the APIs exist, but they are buggy and should not be referenced.
This makes it more precise to avoid introducing buggy libraries.
Also removes unnecessary operator libraries(math_ops,data_flow_ops) compilation and supports compilation under TF2.18.
Run any code use DE Embedding layer in keras eager mode.
> [Fix] Change all "try" version compatibility codes to version detection and remove some libraries.

- .github/workflows/ci_test.yml
- .github/workflows/notify_codeowners.yml
- .github/workflows/release.yml
- demo/dynamic_embedding/movielens-1m-keras-with-horovod/movielens-1m-keras-with-horovod.py
- tensorflow_recommenders_addons/dynamic_embedding/python/kernel_tests/BUILD
- tensorflow_recommenders_addons/dynamic_embedding/python/ops/data_flow_ops.py
dynamic_partition and dynamic_stitch missing compile implementation of the bool data type  in older TensorFlow version.  Now is time to remove TFRA DE same-name op when TensorFlow supports those data type.
Also fix Github CI have been unsupport python3.7
Also fix demo movielens-1m-keras-with-horovod.py. Prefix code for input feature should be in the upper bit.
Profile tensorflow trace view see if there is additional data D-H-D transport.
> [Fix] Remove tests of deprecated operators and adapt to GitHub CI.

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
- [✅] Bug fix
*
Redis cluster mode: all data need to split by slot. Already test in my redis cluster.
> fix redis cluster api: MaccumCommand

- tensorflow_recommenders_addons/dynamic_embedding/core/kernels/redis_impl/redis_cluster_connection_pool.hpp
When there are a large number of client NODES, the initialization commands CLUSTER SLOTS 0 and CLUSTER NODES 0 cause shard 0 in the Redis cluster to exceed the maximum number of connections.
Create a model running with hundreds of Redis tables and distributed in hundreds of nodes sharing same Redis cluster.
> [Fix] Redis cluster to exceed the maximum number of connections
